jda:
  discord:
    token: OTkyMzE0OTc4NTMzMTI2MTg2.GnRMRl.WEx8_M1oCzwTzHkyH-MUpKy_l3lozS7zV9XDvI

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/coinrich
    name: coinrich
    password: coinrich

server:
  servlet:
    jsp:
      init-parameters:
        development: true
    encoding:
      charset: UTF-8
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

apikey:
  upbit:
    accesskey: ENC(9GrDk6LuF8gzjOsJTiwxfa6ofokkmc5DGHVmzCC+ujYsWolHUZ6s2Wpi4zJFxTtIHC9qQ8mohpU=)
    secretkey: ENC(GZfWK4zWdko3v39TLbsnGjY5+fVDk7D09Qib1CtwgyyQLOKhjee9UsQ7hiPfYOnpf4YabcM2FV4=)
  discord:
    token: OTkyMzE0OTc4NTMzMTI2MTg2.GnRMRl.WEx8_M1oCzwTzHkyH-MUpKy_l3lozS7zV9XDvI
    webhook: https://discord.com/api/webhooks/996313509283500052/Wm5lMYrql1eqiQ6-SLhgYQ__k6egts7DWeD6h3EXqPQ9g-rHItYO1jwcOZOz6Cgf1Ccp