spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/coinrich
    name: coinrich
    password: coinrich
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  servlet:
    jsp:
      init-parameters:
        development: true
    encoding:
      charset: UTF-8
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

apikey:
  upbit:
    accesskey: ENC(U460eLqc0ibTtRTwwHlPItJ99xEHvAhCvVNQVWj3zW/n+7+8HbdkB6vedexf20SIALRckqCZj4Y=)
    secretkey: ENC(pLYTdnX0HsHmJr2HzOVJd6TOHLy07YrOn1M/zRunz3hhIgM6Fafr9ibG39b28yZ/BaOH+FpIOMc=)
  discord:
    token: ENC(tal0GN24UKs759U5C8dA6/fljIvBqympxZ6QOs2X5rinxP5zKf+/1ufFCu4wCYmzcWmPG/JMhI0ovu/peP/t/dHrZOt+Isp5QQiUvfcjQzs=)
  generate:
    password: ENC(duX9W2JAPJ5YIRGhagCHcg==)

