spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/coinrich
    name: coinrich
    password: coinrich
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  servlet:
    jsp:
      init-parameters:
        development: true
    encoding:
      charset: UTF-8
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

apikey:
  upbit:
    accesskey: ENC(KsxbfHI1Ib3kUOxu5JXAJ6OKc+zn82vvc8nysODQQgLnltBKK8u/EAHAO+krEWL2S8AsgLVmsSk=)
    secretkey: ENC(gxjS9I2IrivdjVtGF9Ro0N5s0vfNi2ano4hUWAUF6YL5xNE3Mvxb2JP68hfVZ62FgUo0Owvfsa0=)
  discord:
    token: ENC(tal0GN24UKs759U5C8dA6/fljIvBqympxZ6QOs2X5rinxP5zKf+/1ufFCu4wCYmzcWmPG/JMhI0ovu/peP/t/dHrZOt+Isp5QQiUvfcjQzs=)
  generate:
    password: ENC(duX9W2JAPJ5YIRGhagCHcg==)

